### PR TITLE
XRULES-20200606: support query string and proxy

### PR DESCRIPTION
**Pull request by atkaper**
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary Of Changes:
support query string and proxy

### Added
- XRULES-20200606: Add function 'param' to read query string parameters of incoming event url
- XRULES-20200606: Add use of HTTP_PROXY environment variable to send data via a proxy

### Changed
- XRULES-20200606: Docker build; Make smaller runtime image by using multi-stage build, and enable testing

### Fixed
-

## I Have Done The Following
- [x] Updated the `CHANGELOG.md` file with the above summary of changes.
- [x] I have updated the documentation accordingly.
- [x] Have added new unit tests to test any new code.
- [x] Have not reduced code coverage since the last commit (`go test -cover`).
- [x] Confirmed that all existing and new tests passed.

## Reviewers

@xyang200
@gtrevg 
@holidaymike

### CODE REVIEW

**Comment by atkaper** [comment]
Same result in build as last time, can someone please have a look at the failed build? I am guessing it has nothing to do with my change. But if it does, please advise what I need to update to get this running again. Thanks.
@toyangxia @boriwo @gtrevg @holidaymike

**Comment by zeushammer** [comment]
We will get this updated and merged

**Comment by atkaper** [comment]
@zeushammer Any chance you can merge this one? Thanks.

**Comment by atkaper** [comment]
@boriwo  / @zeushammer Any chance you can merge this one? Thanks.

**Review by zeushammer — APPROVED** [review]
Looks good to me. Build looks good. Error is an issue with GO 1.6 and the go get command. 1.7+ builds good.

**Comment by zeushammer** [comment]
@atkaper Thanks very much!

**Comment by atkaper** [comment]
@zeushammer Thanks for merging Andrew!

**Pull request merged**
