### PR TITLE
XRULES-20200606: support query string and proxy

### PR DESCRIPTION
**Pull request by atkaper**
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary Of Changes:
support query string and proxy

### Added
- XRULES-20200606: Add function 'param' to read query string parameters of incoming event url
- XRULES-20200606: Add use of HTTP_PROXY environment variable to send data via a proxy

### Changed
- XRULES-20200606: Docker build; Make smaller runtime image by using multi-stage build, and enable testing

### Fixed
-

## I Have Done The Following
- [x] Updated the `CHANGELOG.md` file with the above summary of changes.
- [x] I have updated the documentation accordingly.
- [x] Have added new unit tests to test any new code.
- [x] Have not reduced code coverage since the last commit (`go test -cover`).
- [x] Confirmed that all existing and new tests passed.

## Reviewers

@xyang200

### CODE REVIEW

**Comment by atkaper** [comment]
@xyang200 can you please have a look at the failed build? I am guessing it has nothing to do with my change. But if it does, please advise what I need to update to get this running again. Thanks.

**Comment by gtrevg** [comment]
@atkaper -- The reason for the failed build is that the `context` package was added to Go in version 1.7.  Travis is trying to build using v1.5.4 and is complaining about not having this package:

```
$ gimme version
v1.5.4
$ go version
go version go1.6 linux/amd64
go.env
$ go env
7.73s$ go get
package context: unrecognized import path "context" (import path does not begin with hostname)
The command "go get" failed and exited with 1 during .
```

@toyangxia @boriwo  Travis should probably be updated to cover more modern versions of go (we're now at v1.14)

**Comment by atkaper** [comment]
@gtrevg Thanks for the feedback. So I guess I will just have to wait for someone to fix travis.

**Comment by holidaymike** [comment]
Also, do you mind create a pull request against the dev branch instead? We normally run QA automation on dev before promoting changes to master. Close this pull request in the meantime.

**Comment by atkaper** [comment]
Next attempt; https://github.com/Comcast/eel/pull/143

**Pull request closed without merging**
